# change my name to app.yml
mysql:
  dns: `name`:`password`@tcp(longsizhuo.com:3306)/`databse_name`?charset=utf8mb4&parseTime=True&loc=Local
  # dns: COMP9900:root@tcp(mingotree.cn:3306)/comp9900?charset=utf8mb4&parseTime=True&loc=Local

#如果连接不上就把longsizhuo.com 改成公网IP：175.178.112.118
redis:
  Addr: "longsizhuo.com:6379" # 备用redis: longsizhuo.com:6379
  Password: "COMP9900"
  DB: 0